### PR TITLE
OpenWrt build system update

### PR DESCRIPTION
**Pull request by dfranusic**
* **opensync_stats.proto** gets compiled during the build process

### CODE REVIEW

**Comment by blogic** [comment]
nice, this has been on my list for a while. we should ask the cloud team to test an image with this patch before we push
@RickSommerville could you help getting aligned with the cloud team on that ?

**Comment by blogic** [comment]
In testing, this patch breaks events for the clouds.

**Comment by dfranusic** [comment]
How do we address this issue? The only connection with the cloud, from our side at least, is the protobuffer definitions (opensync_stats.proto).

**Comment by RickSommerville** [comment]
John:  Which event breaks?  What was tested against?  Did you mean the statistics rather than events?  Or do you mean the build breaks when combined with the earlier pull request for events? 

Damir:  Did you test the various statistics reports against the static gateway with this image?

**Comment by dfranusic** [comment]
Rick: I had no issues with SM reports, as I could clearly see everything being logged in **"opensyncgw.log"**.

**Comment by blogic** [comment]
@RickSommerville You said so when I asked ?!

**Comment by RickSommerville** [comment]
My concern was with the protobuf change, which has already been corrected (by rebasing).

**Comment by blogic** [comment]
ok, let me merge it later today ot tomorrow in that case

**Comment by blogic** [comment]
merged into pending, Thanks !

**Pull request closed without merging**
