### PR TITLE
Staging captive portal

### PR DESCRIPTION
**Pull request by NagConnectus**
Add openNDS package to enable captive portal at bridge level

### CODE REVIEW

**Comment by blogic** [comment]
> Can you please use the patch format as suggested by John?
> opensync: Short description
> Long description

and Signed-off-by: line 
the SoB is the most critical part

**Comment by NagConnectus** [comment]
> Can you please use the patch format as suggested by John?
> opensync: Short description
> Long description

**Comment by NagConnectus** [comment]
> > Can you please use the patch format as suggested by John?
> > opensync: Short description
> > Long description
> 
> and Signed-off-by: line
> the SoB is the most critical part

sure, I'll do that
thank you

**Comment by NagConnectus** [comment]
> Can you please use the patch format as suggested by John?
> opensync: Short description
> Long description

sure ,I'll do that
thank you

**Comment by blogic** [comment]
merged into pending, Thanks !

**Pull request closed without merging**
