### PR TITLE
Statging fixmgmtipreporting

### PR DESCRIPTION
**Pull request by yashvardhan-netex**
opensync nm expects exact interface names or else it does not populate
inet address and related parameters in the wifi inet state table

### CODE REVIEW

**Comment by blogic** [comment]
Hi,
the file being patched here will actually disappear once we merge the new network manager. the values will then be generated directly from what is present inside UCI
  John

**Comment by yashvardhan-netex** [comment]
> Hi,
> the file being patched here will actually disappear once we merge the new network manager. the values will then be generated directly from what is present inside UCI
> John

Hi John,
That sounds good! Are we planning to introduce the new network manager any time soon or before MVP? If not, Can we have this fix for now and change it later with the new nm?
Yash

**Comment by blogic** [comment]
@yashvardhan-netex I am hoping to merge before mondays meeting

**Comment by yashvardhan-netex** [comment]
> @yashvardhan-netex I am hoping to merge before mondays meeting

Great! I think we can wait till then

**Pull request closed without merging**
