### PR TITLE
ipq807x: yuncore ax840 fix WIFI-11972

### PR DESCRIPTION
**Pull request by legale**
# Changes:
- minor changes to the device specification;
- dts flash memory layout added;
- ath11k-firmware package: qdss_trace_config.bin added;
- ath11k-wifi package: board-2.bin fix;
- 10-ath11k-caldata script caldata.bin size fix.

# Hardware specs:
Chipset: Qualcomm IPQ6018 (QCN5052 + QCN5022)
Standard: 802.11ax/ac/b/g/n
Flash: SPI NOR 8MB (MX25U6432F 1.8V) + NAND 128MB (MX30UF1G18AC) 
RAM DDR3L: 512MB
1 * 10/100 /1000 RJ45 WAN Port (PoE)
1 * 10/100 /1000 RJ45 LAN Port
1 * Reset button: GPIO19
Antenna: Build in 3dBi MIMO Antenna x4
RF Power: ≤ 24dBm
DC: 12V 2A
PoE: 48V (IEEE 802.3at)
LED light: Sys, WAN, LAN
Power Consumption: ≤ 24W
Size: 198mm  * 198mm  * 41.02mm

## Stock installation:
	DO FULL SPI AND NAND BACKUP USING TELNET.
	Connect UART and enter UBOOT console.
	exec:
	tftpboot 0x44000000 192.168.1.251:initramfs_image
	bootm

	Flash sysupgrade firmware image via web interface
	or via ssh console: `sysupgrade -n sysupgrade_image`

## Stock direct UBOOT installation:
	exec:
	tftpboot 0x44000000 192.168.1.251:nand_factory_image
	flash rootfs
	reset

## Stock firmware recovery:
	Boot with initramfs image. Copy mtd17 backup to the /tmp.
	exec:
	mtd erase rootfs
	mtd write /tmp/mtd17 rootfs
	reboot

Signed-off-by: Isaev Ruslan <legale.legale@gmail.com>

### CODE REVIEW

**Comment by legale** [comment]
@pepe2k @blogic check it out, please.

**Comment by blogic** [comment]
what is qdss_trace_config.bin actually required for ?

**Comment by legale** [comment]
> what is qdss_trace_config.bin actually required for ?

Wifi Hardware block event masks to debug hardware
watchdog issues, backpressure issues in hardware blocks
are present in the file. The event masks are used as
input by host driver to collect selected events from
Hardware blocks that are collected at run time in host
memory. The collected content is then parsed using
Qualcomm internal scripts to debug Hardware crash issues.

**Comment by pepe2k** [comment]
@legale you fix in [10-ath11k-caldata](https://github.com/Telecominfraproject/wlan-ap/pull/482/commits/a2ee6c2bff7553415fc3eda8e09d203d5a6dbc40#diff-276788f8e301b8d565ca0221d2ba46e2d0757b584f2e06568a997850f8811275) is correct. My suggestion is to drop it from this series and send it as a separated PR (it's a simple fix of obvious rebase/merge mistake).

Adding static partition declaration into `qcom-ipq6018-yuncore-ax840.dts` doesn't make much sense. First of all, partition layout is taken from SMEM with `qcom-smem` parser. What's more, declaring `rootfs` and `rootfs_1` with static offsets will brick some devices. YunCore uses dual-image approach with `rootfs`/`rootfs_1` partitions naming swap (they use QCA "runtime failsafe upgrade"). Some devices will have `rootfs` at offset `0x0`, other at `3c00000` :). I have ready patches with support for that dual-image, will add PR with it shortly so that you can test it.

Regarding `qdss_trace_config.bin`, I don't know the purpose of it but I don't think it will be used by anything in OpenWiFi.

For change in [profiles/yuncore_ax840.yml](https://github.com/Telecominfraproject/wlan-ap/pull/482/files#diff-a10dcc9e4eb8a78376188581fcaf5cec2b0a29497a3fc5fe3ebbb9259b291872), do you have board with 512 MB of RAM? The one I have is 1 GB...

I will look into [feeds/wifi-ax/ath11k-wifi/Makefile](https://github.com/Telecominfraproject/wlan-ap/pull/482/commits/a2ee6c2bff7553415fc3eda8e09d203d5a6dbc40#diff-d10238c8ae4a6f46fd046075db9e76c95710acb571744646f480348039be3466) later.

Cheers,
Piotr

**Comment by pepe2k** [comment]
@legale 
> Thanks for your explanation about nand memory layout. Ready to test your patch.

Here you go: https://github.com/Telecominfraproject/wlan-ap/pull/497

Cheers,
Piotr

**Pull request closed without merging**
