### PR TITLE
WiFi-2072. Populate the right fw version in the AWLAN_Node

### PR DESCRIPTION
**Pull request by netexp-ravi**
Populating the fw version from FW_IMAGE_ACTIVE in the
AWLAN_Node.

Signed-off-by: ravi vaishnav <ravi.vaishnav@netexperience.com>

### CODE REVIEW

**Review by RickSommerville — APPROVED** [review]
Looks good.

**Review by RickSommerville — CHANGES_REQUESTED** [review]
Ravi, this needs to be rebased with the latest,  Conficts with the MODEL change.

**Comment by netexp-ravi** [comment]
> Ravi, this needs to be rebased with the latest, Conficts with the MODEL change.

Done.

**Comment by RickSommerville** [comment]
Merged 7ec23942, thanks

**Pull request closed without merging**
