### PR TITLE
Add support for Mesh++ S618 devices

### PR DESCRIPTION
**Pull request by krishplusplus**
Mesh++ S618 has below models based on Qualcomm IPQ6018:
  * cp03-c1
  * cp01-c1

These are Wi-Fi 6 (IEEE 80211.ax) dual band 2x2 mesh routers.

Signed-off-by: Krishna <krishna@meshplusplus.com>
Signed-off-by: Edward Cheung <edward@meshplusplus.com>

### CODE REVIEW

**Comment by blogic** [comment]
the generic board support patches look fine at first glance, however the profile/ patch heavily deviates from what current TIP data model provides.

**Comment by krishplusplus** [comment]
> the generic board support patches look fine at first glance, however the profile/ patch heavily deviates from what current TIP data model provides.

Can you please elaborate on this? Is the concern about how we are adding support two variants of the hardware? What is the data model in question? How does it tie with profiles?

**Comment by krishplusplus** [comment]
> > the generic board support patches look fine at first glance, however the profile/ patch heavily deviates from what current TIP data model provides.
> 
> Can you please elaborate on this? Is the concern about how we are adding support two variants of the hardware? What is the data model in question? How does it tie with profiles?

**Comment by krishplusplus** [comment]
As per slack discussion, removed `bmx7` related packages as they don't have corresponding `ucentral-schema` changes, thought our device works with default configuration.

**Comment by cbuschfb** [comment]
looks ok to me.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by blogic** [comment]
I removed the patch from the tree, due to typos inside ath11k-wifi it breaks all boards. please make sure to test the patches you send next time round.

**Comment by krishplusplus** [comment]
Apologies, I guess you are referring to missing `endef` in `feeds/wifi-ax/ath11k-wifi/Makefile`? I did test this but it was a last minute change. So, re-open the PR with the fix?

**Comment by krishplusplus** [comment]
@blogic Gentle reminder!

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
