### PR TITLE
APC: relinquish DR/BDR mode on Cloud conn loss

### PR DESCRIPTION
**Pull request by chaitanyagodavarthi**
If there is a cloud connectivity loss, we do not
want the AP to be elected as a DR/BDR since that would
mean the APs configuration could mismatch with all the
other APs linked to it.

Signed-off-by: Chaitanya Godavarthi <chaitanya.kiran@netexperience.com>

### CODE REVIEW

**Review by RickSommerville — CHANGES_REQUESTED** [review]
Github says this code will not merge cleanly,  please rebase.

Why are you polling the Manager table instead of listening for events?
There is an example in command/src/webserver.c that does a listen on the Manager table.
You can improve on that by using a filter so only get notified of "status" changes; see cm2_ovsdb.c/cm2_ovsdb_init() around line 2087 (this is another example of listen on Manager table).

**Comment by chaitanyagodavarthi** [comment]
> Github says this code will not merge cleanly, please rebase.
> 
> Why are you polling the Manager table instead of listening for events?
> There is an example in command/src/webserver.c that does a listen on the Manager table.
> You can improve on that by using a filter so only get notified of "status" changes; see cm2_ovsdb.c/cm2_ovsdb_init() around line 2087 (this is another example of listen on Manager table).

I have rebased the patch. I did initially use the method you mention above, however it would not work in case where the AP always remains in the is_connected=false state from the beginning and doesn't change state at all.  in which case we would not get any events.

**Comment by RickSommerville** [comment]
Could you handle by assuming "not connected" until notified otherwise?

**Comment by chaitanyagodavarthi** [comment]
> Could you handle by assuming "not connected" until notified otherwise?

Ok, In this case we need a one time timer to poll that "not connected" variable.

**Review by RickSommerville — APPROVED** [review]

**Comment by RickSommerville** [comment]
Merged d4oe1f9d, thanks.  WIFI-2343

**Pull request closed without merging**
