### PR TITLE
uci file unload for captive portal

### PR DESCRIPTION
**Pull request by NagConnectus**
This patch will improve the code for captive portal feature

Signed-off-by: Nagendrababu <nagendrababu.bonkuri@connectus.ai>

### CODE REVIEW

**Review by RickSommerville — COMMENTED** [review]
These logs could go away entirely.  They simply indicate OpenNds is inactive.  You have no logs saying the state was updated when OpenNds is active and I don't think you need them.

**Comment by NagConnectus** [comment]
> These logs could go away entirely. They simply indicate OpenNds is inactive. You have no logs saying the state was updated when OpenNds is active and I don't think you need them.

Sure, got it

**Review by RickSommerville — APPROVED** [review]
Looks good

**Comment by RickSommerville** [comment]
Merged 58793d4, thank you

**Pull request closed without merging**
