### PR TITLE
wifi-2512: apc gets stuck in wt mode 1 in 5 reboots

### PR DESCRIPTION
**Pull request by chaitanyagodavarthi**
Check if APC conf is disabled and not update the
APC state.

Signed-off-by: Chaitanya Godavarthi <chaitanya.kiran@netexperience.com>

### CODE REVIEW

**Review by RickSommerville — COMMENTED** [review]
The description says if APC is disabled, then don't update the state.  However, you actually update the state to disabled.  This seems to be implementing all the parameters to disabled.  I can't tell if this will fix the problem.

Do you have a drawing of the state machine for this?  You have a small set of states and events.  I think you can draw it and see whatever race condition is causing issues.

**Comment by chaitanyagodavarthi** [comment]
> The description says if APC is disabled, then don't update the state. However, you actually update the state to disabled. This seems to be implementing all the parameters to disabled. I can't tell if this will fix the problem.
> Do you have a drawing of the state machine for this? You have a small set of states and events. I think you can draw it and see whatever race condition is causing issues.

I have attached an image, for this race condition.
image>

**Comment by RickSommerville** [comment]
OK, I understand the hole being plugged.  Why is the ubus notification WT/true occurring?

**Comment by RickSommerville** [comment]
Merged b2a9e631, thanks

**Pull request closed without merging**
