### PR TITLE
Staging wifi 12943 support oap101 oap101e 6e next2305

### PR DESCRIPTION
**Pull request by tanyasingh-ec**

### CODE REVIEW

**Comment by blogic** [comment]
please use next or next-23.05 branch instead of main

**Comment by tanyasingh-ec** [comment]
> please use next or next-23.05 branch instead of main

This staging branch is based on next-23.05 branch. Is there something additional that I need to do?

**Comment by blogic** [comment]
oh ok, the PR is against main, I will manually merge it

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
