### PR TITLE
Protobuf update

### PR DESCRIPTION
**Pull request by dfranusic**
* session_id correlation for EventReport

### CODE REVIEW

**Comment by RickSommerville** [comment]
Hi Damir,
This pull request appears to delete all of the RTP streaming stats added for voice and video detection.
I don't think it can be used as is.  Do you need to do the pull request against pending not trunk?
Rick Sommerville

**Comment by dfranusic** [comment]
Hi Rick

I'll pull the latest changes from master and update the patch. 

Thanks for the feedback.

**Comment by dfranusic** [comment]
Hi @RickSommerville 

I think the issue is now resolved.

**Comment by blogic** [comment]
merged into pending, Thanks !

**Pull request closed without merging**
