### PR TITLE
ipq807x: include support for 'runtime failsafe' based dual-image on YunCore AX840

### PR DESCRIPTION
**Pull request by pepe2k**
This adds minimal support for so called `runtime failsafe` based dual-image support on the YunCore AX840. Support is minimal in the way that only part of the idea is implemented (as far as I understand it), same as in the original QSDK sources. In short, it allows to switch (rotate) target `rootfs` partition during `sysupgrade` on the boards with dual-image partitions defined, using `BOOTCONFIG` partitions.

Two commits are introduced:
1. **ipq807x: enable BOOTCONFIG partition support in kernel** which enables `BOOTCONFIG_PARTITION` kernel config (a simple driver for handling `BOOTCONFIG` partitions).
2. **ipq807x: include support for dual-image in YunCore AX840** with implementation for partitions rotation in `base-files`.

---

More detailed description is included in the `base-files` patch, quoted here for reference:

During research, when working on support for YunCore AX840 board it was found that this vendor decided to use Qualcomm-made, so called `runtime failsafe` based upgrades from QSDK (see e.g. [1] and [2]).

It turned out that vendor firmware makes use of dual-image feature controlled by `SBL` (not only by `U-Boot` as usual). This mode allows to switch between two copies of firmware in case of a failed upgrade and works not only with kernel/rootfs but apparently, also with other parts of the firmware, like `APPS` (`U-Boot`), Wi-Fi (`ath11k`) firmware, etc. Here, we will focus only on the firmware (in our case, `UBI` on `NAND`).

Two, equal in size, `UBI` partitions are used: the `rootfs` is always the active one (for booting) and `rootfs_1` is used for storing new firmware during the regular `sysupgrade`. Partition names are swapped, probably by the `SBL` (closed-source, second level bootloader), based on layout in `MIBIB` and content of `BOOTCONFIG`/`BOOTCONFIG1` partitions (the second one seems to be only a backup, as mentioned in related kernel driver) and then provided by `SMEM` to U-Boot and kernel. For example:

- when primary `rootfs` partition is `0`:
  0x000000000000-0x000003c00000 : "rootfs"   (used for booting)
  0x000003c00000-0x000007800000 : "rootfs_1"

- when primary `rootfs` partition is `1`:
  0x000000000000-0x000003c00000 : "rootfs_1"
  0x000003c00000-0x000007800000 : "rootfs"   (used for booting)

The whole solution requires support in several other places, including kernel (detecting crash) and U-Boot (partition swap) but this requires more research and apparently, YunCore doesn't even use all of that in a proper way, resulting only in a rotation of firmware partitions during upgrade (without the part responsible for reverting in case of fail during the upgrade).

This patch adds only a small part of the solution, making `dual-image` feature kind of working, resulting in rotation between `rootfs` and `rootfs_1` partitions (areas on NAND) between subsequent updates. This requires also `CONFIG_BOOTCONFIG_PARTITION` support in the kernel and in simple terms, works as follows:

1. Get name of target `rootfs` partition for upgrade from: `/proc/boot_info/rootfs/upgradepartition`.
3. Perform upgrade and in case of success change `primaryboot` flag (`1 -> 0`, `0 -> 1`) for `rootfs` partition in `BOOTCONFIG`.
4. Write back updated `BOOTCONFIG` content to flash: from `/proc/boot_info/getbinary_bootconfig` to mtd partitions (`0:BOOTCONFIG` and `0:BOOTCONFIG1`).

This topic definitely requires additional research if a proper solution (kernel crash and/or failed upgrade detection) is needed so more changes might come in future.

[1] https://git.codelinaro.org/clo/qsdk/oss/kernel/linux-ipq-5.4/-/commit/67225a559ca8e61e87c36a1c9940a085b3950c97
[2] https://git.codelinaro.org/clo/qsdk/oss/system/openwrt_repo/-/blob/NHSS.QSDK.12.1.5.r2/target/linux/ipq60xx/base-files/lib/upgrade/platform.sh#L175

### CODE REVIEW

**Comment by legale** [comment]
@pepe2k, i've tried to flash sysupgrade via web interface with system started from initramfs:

log just after "continue" button pressed.
```
root@OpenWrt:~# [   30.165336] br-lan: port 1(eth0) entered forwarding state
passwd -d root
passwd: password for root changed by root
root@OpenWrt:~# cat /proc/boot_info/rootfs/primaryboot
cat: can't open '/proc/boot_info/rootfs/primaryboot': No such file or directory
root@OpenWrt:~# Watchdog handover: fd=3
- watchdog -
Watchdog does not have CARDRESET support
killall: telnetd: no process killed
Sat Dec  3 06:32:29 UTC 2022 upgrade: Sending TERM to remaining processes ...sh: S: out of range
 logd rpcd spotfilter dnsmasq qosify ubusd unetd hostapd wpa_supplicant netifd odhcpd udhcpsnoop urngd atfpolicy usteerd ustpd udnssnoop ieee8021x ucode umdns accounting.uc ntpd thermald uhttpd
Sat Dec  3 06:32:32 UTC 2022 upgrade: Sending KILL to remaining processes ...sh: S: out of range

[  159.650094] sh (4015): drop_caches: 3
Sat Dec  3 06:32:33 UTC 2022 upgrade: Switching to ramdisk...
Sat Dec  3 06:32:34 UTC 2022 upgrade: Performing system upgrade...
cannot find ubi mtd partition rootfs
libubi: error!: "/dev/" is not a character device
ubiupdatevol: error!: error while probing "/dev/"
              error 22 (Invalid argument)
tar: write error: Broken pipe
libubi: error!: "/dev/" is not a character device
ubiupdatevol: error!: error while probing "/dev/"
              error 22 (Invalid argument)
tar: write error: Broken pipe
sysupgrade successful
umount: can't unmount /dev: Resource busy
umount: can't unmount /tmp: Resource busy
[  161.117531] reboot: Restarting system

Format: Log Type - Time(microsec) - Message - Optional Info
Log Type: B - Since Boot(Power On Reset),  D - Delta,  S - Statist
```

**Comment by legale** [comment]
mtd2 is original BOOTCONFIG from my backup.
BOOTCONFIG is a current BOOTCONFIG partition 
```
root@OpenWrt:/tmp# hexdump -C mtd2
00000000  a0 a1 a2 a3 02 00 00 00  08 00 00 00 30 3a 51 53  |............0:QS|
00000010  45 45 00 00 00 00 00 00  00 00 00 00 01 00 00 00  |EE..............|
00000020  30 3a 44 45 56 43 46 47  00 00 00 00 00 00 00 00  |0:DEVCFG........|
00000030  01 00 00 00 30 3a 52 50  4d 00 00 00 00 00 00 00  |....0:RPM.......|
00000040  00 00 00 00 01 00 00 00  30 3a 43 44 54 00 00 00  |........0:CDT...|
00000050  00 00 00 00 00 00 00 00  01 00 00 00 30 3a 41 50  |............0:AP|
00000060  50 53 42 4c 00 00 00 00  00 00 00 00 01 00 00 00  |PSBL............|
00000070  30 3a 48 4c 4f 53 00 00  00 00 00 00 00 00 00 00  |0:HLOS..........|
00000080  00 00 00 00 72 6f 6f 74  66 73 00 00 00 00 00 00  |....rootfs......|
00000090  00 00 00 00 01 00 00 00  30 3a 57 49 46 49 46 57  |........0:WIFIFW|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000140  00 00 00 00 00 00 00 00  00 00 00 00 b0 b1 b2 b3  |................|
00000150  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00020000
root@OpenWrt:/tmp# hexdump -C BOOTCONFIG
00000000  a0 a1 a2 a3 03 00 00 00  08 00 00 00 30 3a 51 53  |............0:QS|
00000010  45 45 00 00 00 00 00 00  00 00 00 00 01 00 00 00  |EE..............|
00000020  30 3a 44 45 56 43 46 47  00 00 00 00 00 00 00 00  |0:DEVCFG........|
00000030  01 00 00 00 30 3a 52 50  4d 00 00 00 00 00 00 00  |....0:RPM.......|
00000040  00 00 00 00 01 00 00 00  30 3a 43 44 54 00 00 00  |........0:CDT...|
00000050  00 00 00 00 00 00 00 00  01 00 00 00 30 3a 41 50  |............0:AP|
00000060  50 53 42 4c 00 00 00 00  00 00 00 00 01 00 00 00  |PSBL............|
00000070  30 3a 48 4c 4f 53 00 00  00 00 00 00 00 00 00 00  |0:HLOS..........|
00000080  00 00 00 00 72 6f 6f 74  66 73 00 00 00 00 00 00  |....rootfs......|
00000090  00 00 00 00 00 00 00 00  30 3a 57 49 46 49 46 57  |........0:WIFIFW|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000140  00 00 00 00 00 00 00 00  00 00 00 00 b0 b1 b2 b3  |................|
00000150  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00020000

```

**Comment by pepe2k** [comment]
> @pepe2k, i've tried to flash sysupgrade via web interface with system started from **initramfs**:

Why from initramfs?

**Comment by legale** [comment]
It was second try. First one was via sysupgrade. Haven't got log.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
