### PR TITLE
ipq807x: Add ION4XI_WP support

### PR DESCRIPTION
**Pull request by kish-shukla**
Hi,

This PR is to add support for HFCL WIFi6 WallPlate model ION4xi_WP.

### CODE REVIEW

**Comment by jaspreetsachdev** [comment]
@kish-shukla you should create a JIRA and have the JIRA Id in the commit or the PR title to link the two. This way consumers of OpenWiFi can track the new changes. Thank you

**Comment by kish-shukla** [comment]
Sure @jaspreetsachdev .  

Apologies, i forgot to keep this linked with a JIRA!

Noted and will take care of it form now!

**Comment by blogic** [comment]
merged, thanks !

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
