### PR TITLE
netexp-2635:Fix Associated clients in case of roaming

### PR DESCRIPTION
**Pull request by chaitanyagodavarthi**
Associated clients list decrements when client roams
from vifX to vifY. In this case, the client is
first added to the global client list as part of it
associating with vifY (but in actual it doesnt add as
the entry for client already exists) and then deleted
from the same as part of dissassociating from vifX.

Fix is to change the vif the client entry points to
instead of add/delete the client entry.

Signed-off-by: Chaitanya Godavarthi <chaitanya.kiran@netexperience.com>

### CODE REVIEW

**Review by yashvardhan-netex — APPROVED** [review]
Looks good!

**Review by yashvardhan-netex — COMMENTED** [review]
Please update the commit messsage with TIP Jira defect number instead of Netexp

**Review by NagConnectus — APPROVED** [review]
looks good

**Comment by ArifAlam** [comment]
Merged to pending. Thanks.

**Pull request closed without merging**
