### PR TITLE
opensync: add interface name mappings for ECW5410, ECW5211, and AP2220

### PR DESCRIPTION
**Pull request by ArifAlam**

### CODE REVIEW

**Comment by greearb** [comment]
I think you forgot to add the 'Signed-off-By' line?

**Comment by blogic** [comment]
@RickSommerville is currently working on removing the name mapping.

**Comment by RickSommerville** [comment]
Please go ahead with this change to get the other radios working.  The removal of the name mapping is not going smoothly.

**Comment by blogic** [comment]
merged into the pending branch, Thanks !

**Pull request closed without merging**
