### PR TITLE
opensync: add proto definitions for dhcp events

### PR DESCRIPTION
**Pull request by lukakudra**
Signed-off-by: Luka Kudra <luka.kudra@netexperience.com>

### CODE REVIEW

**Comment by AmmadRehmatCUS** [comment]
@RickSommerville 
@lukakudra 

I would just like to make a recommendation to aggregate all the dhcp events like it is done for client session and into one single dhcp event instead of declaring each type of event under client session. Also I believe addition of timestamps in dhcp events would be useful.

**Comment by lukakudra** [comment]
> @RickSommerville
> @lukakudra
> 
> I would just like to make a recommendation to aggregate all the dhcp events like it is done for client session and into one single dhcp event instead of declaring each type of event under client session. Also I believe addition of timestamps in dhcp events would be useful.

The main reason that we aggregated the client connection events into a client session was the fact that we wanted to generate only one event (client connect event) when the connection was successful and generate all the other events when connection was not successful.
Since we don't correlate dhcp events by session_id or any other equivalent value we decided to declare each dhcp event type separately.

That being said, we could still aggregate them into a single message if we agree that this is the best approach. I think that it would make the code easier to read, but I don't see any other significant benefit.

I agree about the timestamps, they should be added.

**Comment by lukakudra** [comment]
Based on the recommendation from @AmmadRehmatCUS we aggregated all the dhcp events into a single dhcp event and added a timestamp in each dhcp event.

**Comment by blogic** [comment]
It appears that this depends on a patch that is not in the tree ?
/tip/pending$ git am 13c8daaf9db84d5178ef35d652dcdb6738fae8da.patch
Applying: opensync: dhcp events proto update
error: feeds/wlan-ap/opensync/patches/24-dhcp-events-proto-definitions.patch: does not exist in index
Patch failed at 0001 opensync: dhcp events proto update
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by dfranusic** [comment]
I'll look into it today and make the necessary adjustments. Thanks.

**Comment by dfranusic** [comment]
It should be fine now. Awaiting your feedback. Thank you.

**Comment by blogic** [comment]
@dfranusic is there already code consuming these data model extensions ?

**Comment by dfranusic** [comment]
@blogic DHCP protobuf models are generated by our StatsManager (@lukakudra) patches, collected and pushed to ubus by the ubus_collector. This should be finished by the end of this week, and we will create a new PR for all of these changes.

**Comment by blogic** [comment]
merged into pending, Thanks !

**Pull request closed without merging**
