### PR TITLE
hostapd: Disconnect client when rssi is low

### PR DESCRIPTION
**Pull request by yashvardhan-netex**
Disconnect client in case rssi drops below the set threshold level

Signed-off-by: Yashvardhan <yashvardhan@netexperience.com>

### CODE REVIEW

**Review by RickSommerville — COMMENTED** [review]
At line 31 in ubus.c something happens to the indentation.

In the 810-client-disconnect-... patch, at line 141 the comment says you don't know if this is going to work.  Does it work?

In

**Comment by yashvardhan-netex** [comment]
> At line 31 in ubus.c something happens to the indentation.
> 
> In the 810-client-disconnect-... patch, at line 141 the comment says you don't know if this is going to work. Does it work?
> 
> In

Indentation taken care in the lates commit c316a9b.
Removed comment at line 141 as it does work.

**Comment by blogic** [comment]
Hi few observations
*) the check should not be happening inside ubus.c
2) why is there a ubus method to update the config ? do we want to change this at runtime ?
3) please split the patch up into logical units. there should be 1 part for the hapd changes, one for the ubus part, ...

**Comment by blogic** [comment]
merged into pending, Thanks !

**Pull request closed without merging**
