### PR TITLE
Staging indio pending jira wifi 10802

### PR DESCRIPTION
**Pull request by mdsohailahmad**
Added Indio 11ax AP models committed under WIFI-10802 to build pipeline

### CODE REVIEW

**Comment by blogic** [comment]
what is the difference between this pr and the already merged 498 ?

**Comment by mdsohailahmad** [comment]
> what is the difference between this pr and the already merged 498 ?

It seems, a duplicate PR was generated. Please ignore if it is already captured in 498.

**Comment by mdsohailahmad** [comment]
> > what is the difference between this pr and the already merged 498 ?
> 
> It seems, a duplicate PR was generated. Please ignore if it is already captured in 498.

I just checked, #498 doesn't include my changes. Please merge #499

**Comment by mdsohailahmad** [comment]
> > > what is the difference between this pr and the already merged 498 ?
> > 
> > 
> > It seems, a duplicate PR was generated. Please ignore if it is already captured in 498.
> 
> I just checked, #498 doesn't include my changes. Please merge #499

@blogic please check and merge PR-499

**Comment by jaspreetsachdev** [comment]
@mdsohailahmad we have failing builds.

**Pull request closed without merging**
